"""
内置默认配置

包含默认配置常量和配置文件模板
"""

from typing import Any, Dict

# 默认配置字典
DEFAULT_CONFIG: Dict[str, Any] = {
    "schema_version": "1.0",
    "api_keys": {},
    "defaults": {
        "llm_provider": "zhipu",
        "llm_model": "glm-4.5-flash",
        "agent_type": "basic",
        "streaming": True,
        "temperature": 0.6,
    },
    "display": {
        "show_welcome": True,
        "enable_colors": True,
        "streaming_refresh_rate": 10,
        "streaming_delay_ms": 50,
    },
    "mcp": {
        "enabled": True,
        "auto_start": True,
        "config_file": "tools/mcp/mcp.toml",
        "tool_call_timeout_ms": 60000,
    },
    "deep_agent": {
        "default_provider": "anthropic",
        "default_model": "claude-4.5-sonnet",
        "max_execution_time": 900,
        "recursion_limit": 300,
    },
    "ollama": {
        "base_url": "http://localhost:11434",
        "timeout": 60,
        "keep_alive": "5m",
        "default_model": "gpt-oss:20b",
    },
    "paths": {
        "llm_providers": "llm/providers.json",
        "basic_agent_providers": "agents/basic/providers.json",
        "deep_agent_subagents": "agents/deep/subagents.json",
        "deep_agent_mainagents": "agents/deep/mainagents.json",
        "mcp_config": "tools/mcp/mcp.toml",
    },
}

# config.toml 模板
DEFAULT_CONFIG_TOML = '''# IRIS Configuration File
# Generated by IRIS CLI
# Documentation: https://github.com/your-repo/iris/docs

schema_version = "1.0"

# =============================================================================
# API Keys Configuration
# =============================================================================
# Use ${ENV_VAR} to reference environment variables (recommended)
# Or set values directly (not recommended for sensitive data)
# Keys can also be set in ~/.iris/.env file

[api_keys]
zhipu_api_key = "${ZHIPU_API_KEY}"
openai_api_key = "${OPENAI_API_KEY}"
anthropic_api_key = "${ANTHROPIC_API_KEY}"
tongyi_api_key = "${TONGYI_API_KEY}"
tavily_api_key = "${TAVILY_API_KEY}"
amap_api_key = "${AMAP_API_KEY}"
notion_token = "${NOTION_TOKEN}"

# =============================================================================
# Default Settings
# =============================================================================

[defaults]
llm_provider = "zhipu"      # zhipu, openai, anthropic, ollama
llm_model = "glm-4.5-flash" # Model to use
agent_type = "basic"        # basic, deep
streaming = true            # Enable streaming output
temperature = 0.6           # LLM temperature

# =============================================================================
# Display Settings
# =============================================================================

[display]
show_welcome = true
enable_colors = true
streaming_refresh_rate = 10
streaming_delay_ms = 50

# =============================================================================
# Ollama Configuration (for local models)
# =============================================================================

[ollama]
base_url = "http://localhost:11434"
timeout = 60
keep_alive = "5m"
default_model = "gpt-oss:20b"

# =============================================================================
# MCP Configuration
# =============================================================================

[mcp]
enabled = true
auto_start = true
config_file = "tools/mcp/mcp.toml"
tool_call_timeout_ms = 60000

# =============================================================================
# Deep Agent Configuration
# =============================================================================

[deep_agent]
default_provider = "anthropic"
default_model = "claude-4.5-sonnet"
max_execution_time = 900
recursion_limit = 300

# =============================================================================
# Configuration File Paths (relative to ~/.iris/)
# =============================================================================

[paths]
llm_providers = "llm/providers.json"
basic_agent_providers = "agents/basic/providers.json"
deep_agent_subagents = "agents/deep/subagents.json"
deep_agent_mainagents = "agents/deep/mainagents.json"
mcp_config = "tools/mcp/mcp.toml"
'''

# .env 模板
DEFAULT_ENV_TEMPLATE = '''# IRIS Global Environment Variables
# This file is loaded automatically when running iris from any directory
# Copy this file to .env and fill in your API keys

# =============================================================================
# LLM Providers
# =============================================================================
ZHIPU_API_KEY=your_zhipu_api_key_here
OPENAI_API_KEY=your_openai_api_key_here
ANTHROPIC_API_KEY=your_anthropic_api_key_here
TONGYI_API_KEY=your_tongyi_api_key_here

# OpenAI-compatible API (optional, for custom endpoints)
# OPENAI_BASE_URL=https://api.openai.com/v1

# =============================================================================
# Tool Services
# =============================================================================
TAVILY_API_KEY=your_tavily_api_key_here
AMAP_API_KEY=your_amap_api_key_here
NOTION_TOKEN=your_notion_token_here

# =============================================================================
# Ollama (local models)
# =============================================================================
# OLLAMA_BASE_URL=http://localhost:11434
'''

# 配置文件迁移映射表
# 从项目 config/ 目录到 ~/.iris/ 的映射
CONFIG_MIGRATION_MAPPING: Dict[str, str] = {
    "config/llm/models/providers.json": "llm/providers.json",
    "config/agents/basic/models/providers.json": "agents/basic/providers.json",
    "config/agents/deep/subagents.example.json": "agents/deep/subagents.json",
    "config/agents/deep/mainagents.example.json": "agents/deep/mainagents.json",
    "config/agents/deep/models/subagents.json": "agents/deep/subagents.json",
    "config/agents/deep/models/mainagents.json": "agents/deep/mainagents.json",
    "config/agents/deep/middleware/filesystem/real_filesystem.json": "agents/deep/middleware/filesystem/real_filesystem.json",
    "config/agents/deep/middleware/filesystem/virtual_filesystem.json": "agents/deep/middleware/filesystem/virtual_filesystem.json",
    "config/agents/deep/middleware/shell.json": "agents/deep/middleware/shell.json",
    "config/tools/mcp/mcp.toml": "tools/mcp/mcp.toml",
    "config/tools/sdk/tavily/config.json": "tools/sdk/tavily.json",
    "config/tools/sdk/zhipu/zhipu_search.json": "tools/sdk/zhipu_search.json",
    "config/tools/sdk/zhipu/zhipu_crawl.json": "tools/sdk/zhipu_crawl.json",
    "config/tools/sdk/search/duckduckgo.json": "tools/sdk/duckduckgo.json",
}

# 需要创建的目录列表
REQUIRED_DIRS = [
    "llm",
    "agents/basic",
    "agents/deep/middleware/filesystem",
    "tools/mcp",
    "tools/sdk",
    "sessions",
]
